services:
  mongodb:
    image: mongo:7.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: gost-formatter
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d
    networks:
      - gost-network

  mongo-express:
    image: mongo-express:1.0.0
    restart: unless-stopped
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_URL: mongodb://admin:password123@mongodb:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: password123
      ME_CONFIG_MONGODB_ENABLE_ADMIN: true
      ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - gost-network

volumes:
  mongodb_data:
    driver: local

networks:
  gost-network:
    driver: bridge 